# Generated by Django 4.2.5 on 2023-10-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveBigIntegerField(default=123456789000, unique=True),
        ),
    ]
