# Generated by Django 4.2.5 on 2023-10-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('SAV', 'Savings'), ('CUR', 'Current')], default='SAV', max_length=3),
        ),
    ]
