# Generated by Django 4.2.5 on 2023-10-10 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_remove_account_account_type_userprofile_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_type', models.CharField(choices=[('SAV', 'Savings'), ('CUR', 'Current')], default='SAV', max_length=3)),
                ('account_number', models.PositiveBigIntegerField(unique=True)),
                ('mpin', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_account',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='deposit',
            name='registration',
            field=models.ForeignKey(default=100000000000, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='main_api.useraccount'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver_registration',
            field=models.ForeignKey(default=100000000000, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='main_api.useraccount'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_registration',
            field=models.ForeignKey(default=100000000000, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='main_api.useraccount'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='registration',
            field=models.ForeignKey(default=100000000000, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='main_api.useraccount'),
        ),
    ]
